[sdl]
output=surface
[dosbox]
memsize=16
captures=/home/cosmo/Git/wasm-fist/tools/oracle/_audcap
[cpu]
core=auto
cputype=auto
cycles=max
[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
[autoexec]
mount c /home/cosmo/Git/wasm-fist/armoredfist
c:
LOADGAME -K400,0,1000 -X5000 FIST.RUN
