/* re_out/fist_snd.c -- Armored Fist SND DRIVER-OVERLAY translation unit.
 * GENERATED by tools/assemble_fist.py from the pristine driver decompile. DO NOT EDIT.
 * Corrections go in patches/NNN-*.diff (applied by `make patch`); regenerate with `make assemble`.
 */
#include "ghidra_compat.h"

/* runtime load base (module-relative accessors add it); defined at end, declared here */
extern uint32_t fist_snd_base;

/* ---- driver-unit symbol namespacing (avoid engine-unit link collisions) ---- */
#define FUN_0000_0004 m_snd_FUN_0000_0004
#define FUN_0000_0155 m_snd_FUN_0000_0155
#define FUN_0000_019a m_snd_FUN_0000_019a
#define FUN_0000_01bc m_snd_FUN_0000_01bc
#define FUN_0000_0313 m_snd_FUN_0000_0313
#define FUN_0000_05c4 m_snd_FUN_0000_05c4
#define FUN_0000_05ca m_snd_FUN_0000_05ca
#define FUN_0000_0643 m_snd_FUN_0000_0643
#define FUN_0000_0714 m_snd_FUN_0000_0714
#define FUN_0000_074f m_snd_FUN_0000_074f
#define FUN_0000_0759 m_snd_FUN_0000_0759
#define FUN_0000_0772 m_snd_FUN_0000_0772
#define FUN_0000_0826 m_snd_FUN_0000_0826
#define FUN_0000_0833 m_snd_FUN_0000_0833
#define FUN_0000_088f m_snd_FUN_0000_088f
#define FUN_0000_0966 m_snd_FUN_0000_0966
#define FUN_0000_0997 m_snd_FUN_0000_0997
#define FUN_0000_0aa7 m_snd_FUN_0000_0aa7
#define FUN_0000_0af0 m_snd_FUN_0000_0af0
#define FUN_0000_0af4 m_snd_FUN_0000_0af4
#define FUN_0000_0b80 m_snd_FUN_0000_0b80
#define FUN_0000_0bf7 m_snd_FUN_0000_0bf7
#define FUN_0000_0c94 m_snd_FUN_0000_0c94
#define FUN_0000_0ca9 m_snd_FUN_0000_0ca9
#define FUN_0000_0cd1 m_snd_FUN_0000_0cd1
#define FUN_0000_0cf3 m_snd_FUN_0000_0cf3
#define FUN_0000_0cfb m_snd_FUN_0000_0cfb
#define FUN_0000_0d49 m_snd_FUN_0000_0d49
#define FUN_0000_0d66 m_snd_FUN_0000_0d66
#define FUN_0000_0d67 m_snd_FUN_0000_0d67
#define FUN_0000_0d90 m_snd_FUN_0000_0d90
#define FUN_0000_0dc9 m_snd_FUN_0000_0dc9
#define FUN_0000_0e94 m_snd_FUN_0000_0e94
#define FUN_0000_0ef5 m_snd_FUN_0000_0ef5
#define FUN_0000_1b3c m_snd_FUN_0000_1b3c
#define FUN_0000_1c8f m_snd_FUN_0000_1c8f
#define FUN_0000_216b m_snd_FUN_0000_216b
#define FUN_0000_2187 m_snd_FUN_0000_2187
#define FUN_0000_2196 m_snd_FUN_0000_2196
#define FUN_0000_224c m_snd_FUN_0000_224c
#define FUN_0000_2278 m_snd_FUN_0000_2278
#define FUN_0000_25eb m_snd_FUN_0000_25eb
#define FUN_0000_386d m_snd_FUN_0000_386d
#define app_entry m_snd_app_entry
#define func_0x0000fc4a m_snd_func_0x0000fc4a
#define func_0x000a866b m_snd_func_0x000a866b
#define stack0x0000 m_snd_stack0x0000
#define stack0x4cf4 m_snd_stack0x4cf4
#define stack0x99fe m_snd_stack0x99fe
/* ---- RULE 7: unresolved indirect/mid-function call targets, stubbed (OPEN) ---- */
int func_0x0000fc4a(){ return 0; }  /* OPEN: unresolved indirect/mid-function call target */
int func_0x000a866b(){ return 0; }  /* OPEN: unresolved indirect/mid-function call target */
/* ---- RULE 7b: referenced-but-undefined FUN_/thunk_ targets, stubbed (OPEN) ---- */
/* ---- RULE 8: unbound register/stack pseudo-vars (OPEN: shared globals, not the real files) ---- */
undefined1 stack0x0000;  /* OPEN: SP-relative stack slot modelled as a shared global */
undefined1 stack0x4cf4;  /* OPEN: SP-relative stack slot modelled as a shared global */
undefined1 stack0x99fe;  /* OPEN: SP-relative stack slot modelled as a shared global */

/* ---- forward declarations (every engine function; from the decompile markers) ---- */
void __allregs app_entry(void);
void __allregs FUN_0000_0004(void);
void __allregs FUN_0000_0155(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4, undefined2 *param_5,undefined2 param_6,undefined2 param_7,char param_8);
void __allregs FUN_0000_019a(undefined2 param_1);
void __allregs FUN_0000_01bc(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4, undefined2 *param_5,undefined2 param_6,undefined2 param_7);
void __allregs FUN_0000_0313(char param_1,int param_2,int param_3);
void __allregs FUN_0000_05c4(void);
undefined2 __allregs FUN_0000_05ca(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 *param_4, undefined2 param_5,int param_6);
undefined2 __allregs FUN_0000_0643(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4);
undefined1 __allregs FUN_0000_0714(undefined2 param_1);
void __allregs FUN_0000_074f(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4);
void __allregs FUN_0000_0759(undefined2 param_1,undefined2 param_2,int param_3,undefined2 *param_4, undefined2 param_5,undefined2 param_6);
undefined2 __allregs FUN_0000_0772(undefined2 param_1);
undefined2 __allregs FUN_0000_0826(undefined1 param_1,undefined2 param_2,undefined2 *param_3);
void __allregs FUN_0000_0833(uint param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4);
undefined2 __allregs FUN_0000_088f(int param_1,undefined2 param_2,undefined2 *param_3);
undefined2 __allregs FUN_0000_0966(byte param_1,undefined2 param_2);
void __allregs FUN_0000_0997(byte param_1,int param_2,undefined2 param_3);
undefined4 __allregs FUN_0000_0aa7(undefined2 param_1,uint param_2);
void __allregs FUN_0000_0af0(undefined2 param_1,undefined2 param_2);
void __allregs FUN_0000_0af4(uint param_1,int param_2);
undefined1 __allregs FUN_0000_0b80(undefined2 param_1,char param_2,int param_3,int param_4,undefined2 *param_5, int param_6);
void __allregs FUN_0000_0bf7(undefined2 param_1);
void __allregs FUN_0000_0c94(undefined2 param_1);
void __allregs FUN_0000_0ca9(uint param_1,undefined2 param_2);
undefined2 __allregs FUN_0000_0cd1(byte param_1,byte param_2,int param_3,int param_4,int param_5,undefined2 *param_6, undefined1 *param_7);
void __allregs FUN_0000_0cf3(byte param_1,undefined2 param_2);
void __allregs FUN_0000_0cfb(byte param_1,uint param_2);
undefined2 __allregs FUN_0000_0d49(undefined2 param_1);
undefined4 __allregs FUN_0000_0d66(void);
undefined1 __allregs FUN_0000_0d67(undefined1 param_1);
undefined1 __allregs FUN_0000_0d90(undefined1 param_1);
void __allregs FUN_0000_0dc9(void);
ulong __allregs FUN_0000_0e94(uint param_1,int param_2,int param_3,undefined2 *param_4,int param_5,uint *param_6);
undefined2 __allregs FUN_0000_0ef5(void);
uint __allregs FUN_0000_1b3c(int param_1,undefined2 param_2,undefined2 param_3,int param_4,int param_5, undefined2 param_6,uint param_7);
undefined2 __allregs FUN_0000_1c8f(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4, undefined2 param_5,undefined2 param_6,undefined2 param_7);
undefined2 __allregs FUN_0000_216b(undefined2 param_1);
undefined2 __allregs FUN_0000_2187(void);
void __allregs FUN_0000_2196(void);
uint __allregs FUN_0000_224c(int param_1,int param_2,undefined2 *param_3);
void __allregs FUN_0000_2278(void);
void __allregs FUN_0000_25eb(int param_1);
void __allregs FUN_0000_386d(undefined2 param_1,int param_2,undefined2 param_3,undefined2 param_4, undefined2 *param_5,int param_6,char *param_7);

/* ---- RULE 2: DAT_SEG_OFF -> g_mem accessor at linear (SEG<<4)+OFF ---- */
#define DAT_0000_005a (*(undefined2 *)(g_mem+fist_snd_base+0x5a))
#define DAT_0000_0598 (*(undefined2 *)(g_mem+fist_snd_base+0x598))
#define DAT_0000_059a (*(undefined2 *)(g_mem+fist_snd_base+0x59a))
#define DAT_0000_059c (*(undefined2 *)(g_mem+fist_snd_base+0x59c))
#define DAT_0000_059e (*(undefined2 *)(g_mem+fist_snd_base+0x59e))
#define DAT_0000_05a0 (*(undefined2 *)(g_mem+fist_snd_base+0x5a0))
#define DAT_0000_05a4 (*(undefined2 *)(g_mem+fist_snd_base+0x5a4))
#define DAT_0000_05a6 (*(undefined2 *)(g_mem+fist_snd_base+0x5a6))
#define DAT_0000_05ba (*(undefined2 *)(g_mem+fist_snd_base+0x5ba))
#define DAT_0000_05c2 (*(undefined2 *)(g_mem+fist_snd_base+0x5c2))
#define DAT_0000_0831 (*(undefined2 *)(g_mem+fist_snd_base+0x831))
#define DAT_1000_c002 (*(undefined2 *)(g_mem+0x1c002))
#define DAT_1000_c004 (*(undefined2 *)(g_mem+0x1c004))
#define DAT_1000_c006 (*(undefined2 *)(g_mem+0x1c006))
#define DAT_1000_c008 (*(undefined2 *)(g_mem+0x1c008))
#define DAT_1000_c00a (*(undefined2 *)(g_mem+0x1c00a))
#define DAT_1000_c00c (*(undefined2 *)(g_mem+0x1c00c))
#define DAT_1000_c00e (*(undefined2 *)(g_mem+0x1c00e))
#define DAT_1000_c010 (*(undefined2 *)(g_mem+0x1c010))
#define DAT_1000_c012 (*(undefined2 *)(g_mem+0x1c012))
#define DAT_1000_c014 (*(undefined2 *)(g_mem+0x1c014))
#define DAT_1000_c03e (*(undefined2 *)(g_mem+0x1c03e))
#define DAT_1000_c05c (*(undefined2 *)(g_mem+0x1c05c))
#define DAT_1000_c1a5 (*(undefined2 *)(g_mem+0x1c1a5))
#define DAT_1000_c1c1 (*(undefined2 *)(g_mem+0x1c1c1))
#define DAT_1000_c5a8 (*(undefined2 *)(g_mem+0x1c5a8))
#define DAT_1000_ce8b (*(undefined2 *)(g_mem+0x1ce8b))
#define DAT_2000_4d02 (*(undefined2 *)(g_mem+0x24d02))
#define DAT_2000_62a1 (*(undefined2 *)(g_mem+0x262a1))
#define DAT_2000_65a4 (*(undefined2 *)(g_mem+0x265a4))
#define DAT_2000_b702 (*(undefined2 *)(g_mem+0x2b702))
#define DAT_2000_c2f2 (*(undefined2 *)(g_mem+0x2c2f2))
#define _DAT_1000_c000 (*(undefined4 *)(g_mem+0x1c000))
#define _DAT_1000_c002 (*(undefined4 *)(g_mem+0x1c002))
#define _DAT_1000_c004 (*(undefined4 *)(g_mem+0x1c004))
#define _DAT_1000_c006 (*(undefined4 *)(g_mem+0x1c006))
#define _DAT_1000_c008 (*(undefined4 *)(g_mem+0x1c008))
#define _DAT_1000_c00a (*(undefined4 *)(g_mem+0x1c00a))
#define _DAT_1000_c00c (*(int **)(g_mem+0x1c00c))
#define _DAT_1000_c00e (*(undefined4 *)(g_mem+0x1c00e))
#define _DAT_1000_c010 (*(undefined4 *)(g_mem+0x1c010))
#define _DAT_1000_c012 (*(undefined4 *)(g_mem+0x1c012))
#define _DAT_1000_c014 (*(undefined4 *)(g_mem+0x1c014))
#define _DAT_1000_c016 (*(undefined4 *)(g_mem+0x1c016))
#define _DAT_1000_c02a (*(undefined4 *)(g_mem+0x1c02a))
#define _DAT_1000_c1a5 (*(undefined4 *)(g_mem+0x1c1a5))
#define _DAT_1000_c1c1 (*(undefined4 *)(g_mem+0x1c1c1))
#define _DAT_1000_c390 (*(undefined4 *)(g_mem+0x1c390))
#define _DAT_1000_c43e (*(undefined4 *)(g_mem+0x1c43e))
#define _DAT_1000_c5b6 (*(undefined4 *)(g_mem+0x1c5b6))
#define _DAT_1000_c5b8 (*(undefined4 *)(g_mem+0x1c5b8))
#define _DAT_1000_c5c0 (*(undefined4 *)(g_mem+0x1c5c0))
#define _DAT_1000_cc31 (*(undefined4 *)(g_mem+0x1cc31))
#define _DAT_1000_d3e2 (*(undefined4 *)(g_mem+0x1d3e2))
#define _DAT_2000_988e (*(undefined4 *)(g_mem+0x2988e))
/* ---- RULE 3: s_ string symbols -> pointer to string bytes in g_mem ---- */
/* ---- RULE 4: absolute RAM accessors -> g_mem ---- */
#define bRam0001c861 (*(undefined1 *)(g_mem+0x1c861))
#define bRam0001c862 (*(undefined1 *)(g_mem+0x1c862))
#define iRam00000020 (*(int *)(g_mem+fist_snd_base+0x20))
#define iRam00000022 (*(int *)(g_mem+fist_snd_base+0x22))
#define iRam000025ec (*(int *)(g_mem+fist_snd_base+0x25ec))
#define iRam000025ee (*(int *)(g_mem+fist_snd_base+0x25ee))
#define iRam000025f0 (*(int *)(g_mem+fist_snd_base+0x25f0))
#define iRam000f0002 (*(int *)(g_mem+0xf0002))
#define ppuRam000f000c (*(undefined2 ***)(g_mem+0xf000c))
#define uRam000f0000 (*(undefined2 *)(g_mem+0xf0000))
#define uRam000f0002 (*(undefined2 *)(g_mem+0xf0002))
#define uRam000f0004 (*(undefined2 *)(g_mem+0xf0004))
#define uRam000f0006 (*(undefined2 *)(g_mem+0xf0006))
#define uRam000f0008 (*(undefined2 *)(g_mem+0xf0008))
#define uRam000f000a (*(undefined2 *)(g_mem+0xf000a))
#define uRam000f000c (*(undefined2 *)(g_mem+0xf000c))
#define uRam000f000e (*(undefined2 *)(g_mem+0xf000e))
#define uRam000f0010 (*(undefined2 *)(g_mem+0xf0010))
#define uRam000f0014 (*(undefined2 *)(g_mem+0xf0014))

/* ===================== engine function bodies (verbatim from the decompile) ===================== */

/* ===== app_entry @ 0000:0000 ===== */

void __allregs app_entry(void)

{
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0004) @ 0000:0004 ===== */

void __allregs FUN_0000_0004(void)

{
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0155) @ 0000:0155 ===== */

/* WARNING: Removing unreachable block (ram,0x00000159) */
/* WARNING: Variable defined which should be unmapped: param_8 */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs
FUN_0000_0155(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,
             undefined2 *param_5,undefined2 param_6,undefined2 param_7,char param_8)

{
  char cVar1;
  undefined1 uVar2;
  undefined2 uVar3;
  undefined2 extraout_DX;
  undefined2 uVar4;
  undefined2 **ppuVar5;
  undefined2 unaff_ES;
  undefined2 unaff_CS;
  undefined2 *puStack_2;
  
  ppuVar5 = &puStack_2;
  ppuRam000f000c = &puStack_2;
  cVar1 = '\x1a';
  puStack_2 = param_5;
  do {
    param_5 = param_5 + -1;
    ppuVar5 = ppuVar5 + -1;
    *ppuVar5 = (undefined2 *)*param_5;
    cVar1 = cVar1 + -1;
  } while ('\0' < cVar1);
  uRam000f0014 = 1;
  uRam000f000e = 0x1c00;
  uRam000f0000 = param_1;
  uRam000f0002 = param_4;
  uRam000f0004 = param_2;
  uRam000f0006 = param_3;
  uRam000f0008 = param_6;
  uRam000f000a = param_7;
  uRam000f0010 = unaff_ES;
  fist_int_dispatch();
  uVar3 = uRam000f0004;
  uVar4 = uRam000f0002;
  (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c43e)))();
  uVar2 = 1;
  if ((param_8 != 'I') && (uVar2 = 2, param_8 != 'T')) {
    uVar2 = 3;
    if ((param_8 != 'A') && ((uVar2 = 3, param_8 != 'C' && (uVar2 = 4, param_8 != 'R')))) {
      uVar2 = 0;
    }
  }
  FUN_0000_0833(CONCAT11(0x30,uVar2),uVar3,extraout_DX,uVar4);
  (*(code *)fist_icall(fist_snd_base+0x0u+(uint16_t)(*(undefined2 *)0x12)))();
  (*(code *)fist_icall(fist_snd_base+0x0u+(uint16_t)(*(undefined2 *)0x26)))();
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_019a) @ 0000:019a ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs FUN_0000_019a(undefined2 param_1)

{
  undefined2 extraout_DX;
  undefined2 uVar1;
  undefined2 unaff_CS;
  
  (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c016)))();
  (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c02a)))();
  uVar1 = extraout_DX;
  FUN_0000_0833(0x9000,param_1,extraout_DX,unaff_CS);
  FUN_0000_0833(0x3000,param_1,uVar1,unaff_CS);
  (*(code *)fist_icall(fist_snd_base+0x0u+(uint16_t)(*(undefined2 *)0x442)))(0);
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_01bc) @ 0000:01bc ===== */

/* WARNING: Removing unreachable block (ram,0x000001c0) */

void __allregs
FUN_0000_01bc(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,
             undefined2 *param_5,undefined2 param_6,undefined2 param_7)

{
  char cVar1;
  undefined2 **ppuVar2;
  undefined2 unaff_ES;
  undefined2 *puStack_2;
  
  ppuVar2 = &puStack_2;
  ppuRam000f000c = &puStack_2;
  cVar1 = '\x1a';
  puStack_2 = param_5;
  do {
    param_5 = param_5 + -1;
    ppuVar2 = ppuVar2 + -1;
    *ppuVar2 = (undefined2 *)*param_5;
    cVar1 = cVar1 + -1;
  } while ('\0' < cVar1);
  uRam000f0014 = 1;
  uRam000f000e = 0x1c00;
  uRam000f0000 = param_1;
  uRam000f0002 = param_4;
  uRam000f0004 = param_2;
  uRam000f0006 = param_3;
  uRam000f0008 = param_6;
  uRam000f000a = param_7;
  uRam000f0010 = unaff_ES;
  fist_int_dispatch();
  (*(code *)fist_icall(fist_snd_base+0x0u+(uint16_t)(*(undefined2 *)0x442)))();
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0313) @ 0000:0313 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs FUN_0000_0313(char param_1,int param_2,int param_3)

{
  *(char *)(param_2 + param_3) = *(char *)(param_2 + param_3) + param_1;
  *(char *)(param_2 + param_3) = *(char *)(param_2 + param_3) + param_1;
  *(char *)(param_2 + param_3) = *(char *)(param_2 + param_3) + param_1;
  *(char *)(param_2 + param_3) = *(char *)(param_2 + param_3) + param_1;
  (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c390)))();
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_05c4) @ 0000:05c4 ===== */

void __allregs FUN_0000_05c4(void)

{
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_05ca) @ 0000:05ca ===== */

/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __allregs
FUN_0000_05ca(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 *param_4,
             undefined2 param_5,int param_6)

{
  byte *pbVar1;
  code *pcVar2;
  undefined2 uVar3;
  undefined2 uVar4;
  code *pcVar5;
  char cVar6;
  byte bVar7;
  undefined2 **ppuVar8;
  undefined1 *puVar9;
  undefined1 *puVar10;
  undefined1 *puVar11;
  int unaff_ES;
  byte bVar12;
  byte in_AF;
  byte in_TF;
  byte in_IF;
  bool bVar13;
  byte in_NT;
  undefined2 *puStack_2;
  
  ppuVar8 = &puStack_2;
  cVar6 = '\x1d';
  puStack_2 = param_4;
  do {
    param_4 = param_4 + -1;
    ppuVar8 = ppuVar8 + -1;
    *ppuVar8 = (undefined2 *)*param_4;
    cVar6 = cVar6 + -1;
  } while ('\0' < cVar6);
  pbVar1 = (byte *)(param_6 + 4);
  bVar7 = (byte)((uint)param_2 >> 8);
  bVar12 = CARRY1(*pbVar1,bVar7);
  *pbVar1 = *pbVar1 + bVar7;
  pcVar2 = _DAT_1000_c5c0;
  puVar9 = (undefined1 *)(unaff_ES + -2);
  *(undefined2 *)(unaff_ES + -2) = 0x5d7;
  (*pcVar2)();
  uVar4 = DAT_0000_005a;
  DAT_1000_c05c = DAT_1000_c05c + -1;
  _DAT_1000_c5b8 = _DAT_1000_c5b8 + -1;
  if (_DAT_1000_c5b8 != 0) {
    bVar13 = SBORROW2(DAT_0000_05ba,1);
    DAT_0000_05ba = DAT_0000_05ba + -1;
    if (DAT_0000_05ba != 0) {
      out(0x20,0x20);
      return *(undefined2 *)(puVar9 + 6);
    }
    *(uint *)(puVar9 + -2) =
         (uint)(in_NT & 1) * 0x4000 | (uint)bVar13 * 0x800 | (uint)(in_IF & 1) * 0x200 |
         (uint)(in_TF & 1) * 0x100 | 0x40 | (uint)(in_AF & 1) * 0x10 | 4 | (uint)(bVar12 & 1);
    uVar3 = ((undefined2 *)0x432)[1];
    pcVar5 = (code *)*(undefined2 *)0x432;
    *(undefined2 *)(puVar9 + -4) = 0;
    puVar10 = puVar9 + -6;
    *(undefined2 *)(puVar9 + -6) = 0x5fb;
    (*pcVar5)();
    return *(undefined2 *)(puVar10 + 6);
  }
  out(0x20,0x20);
  *(undefined2 *)(puVar9 + -2) = param_3;
  *(undefined2 *)(puVar9 + -4) = param_1;
  *(undefined2 ***)((int)puVar9 + -6) = &puStack_2;
  *(int *)(puVar9 + -8) = param_6;
  *(undefined2 *)(puVar9 + -10) = param_5;
  if (DAT_1000_c05c == -1) {
    in(0x3da);
    bVar12 = 0;
  }
  _DAT_1000_c5b8 = _DAT_1000_c5b6;
  DAT_1000_c5a8 = DAT_1000_c5a8 + '\x01';
  uVar4 = ((undefined2 *)0x42e)[1];
  pcVar5 = (code *)*(undefined2 *)0x42e;
  *(undefined2 *)(puVar9 + -0xc) = 0;
  puVar11 = puVar9 + -0xe;
  *(undefined2 *)(puVar9 + -0xe) = 0x631;
  (*pcVar5)();
  DAT_0000_05ba = (uint)bVar12;
  return *(undefined2 *)(puVar11 + 0x10);
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0643) @ 0000:0643 ===== */

undefined2 __allregs
FUN_0000_0643(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4)

{
  undefined1 uVar1;
  undefined1 extraout_AH;
  uint uVar2;
  
  if (DAT_0000_059a != 0 || DAT_0000_0598 != 0) {
    iRam00000020 = DAT_0000_0598;
    iRam00000022 = DAT_0000_059a;
    DAT_0000_0598 = 0;
    DAT_0000_059a = 0;
    param_1 = DAT_0000_05a0;
    FUN_0000_0714(DAT_0000_05a0);
  }
  FUN_0000_074f(param_1,param_2,param_3,param_4);
  uVar1 = in(0x61);
  uVar2 = CONCAT11(extraout_AH,uVar1) & 0xfffc;
  out(0x61,(char)uVar2);
  out(0x43,0xb6);
  return CONCAT11((char)(uVar2 >> 8),0xb6);
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0714) @ 0000:0714 ===== */

undefined1 __allregs FUN_0000_0714(undefined2 param_1)

{
  undefined1 uVar1;
  
  out(0x43,0x36);
  out(0x40,(char)param_1);
  uVar1 = (undefined1)((uint)param_1 >> 8);
  out(0x40,uVar1);
  return uVar1;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_074f) @ 0000:074f ===== */

/* WARNING: Removing unreachable block (ram,0x00000764) */

void __allregs
FUN_0000_074f(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4)

{
  undefined2 unaff_ES;
  
  if ((DAT_0000_059e | DAT_0000_059c) != 0) {
    uRam000f0014 = 0x21;
    uRam000f0000 = 0x250f;
    uRam000f0006 = DAT_0000_059c;
    uRam000f000e = DAT_0000_059e;
    uRam000f0002 = param_1;
    uRam000f0004 = DAT_0000_059e | DAT_0000_059c;
    uRam000f0008 = param_3;
    uRam000f000a = param_4;
    uRam000f000c = param_2;
    uRam000f0010 = unaff_ES;
    fist_int_dispatch();
    DAT_0000_0598 = 0;
    DAT_0000_059a = 0;
  }
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0759) @ 0000:0759 ===== */

/* WARNING: Removing unreachable block (ram,0x00000764) */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs
FUN_0000_0759(undefined2 param_1,undefined2 param_2,int param_3,undefined2 *param_4,
             undefined2 param_5,undefined2 param_6)

{
  char cVar1;
  undefined2 **ppuVar2;
  undefined2 unaff_ES;
  byte in_CF;
  undefined2 *puStack_2;
  
  ppuVar2 = &puStack_2;
  ppuRam000f000c = &puStack_2;
  cVar1 = '\x13';
  puStack_2 = param_4;
  do {
    param_4 = param_4 + -1;
    ppuVar2 = ppuVar2 + -1;
    *ppuVar2 = (undefined2 *)*param_4;
    cVar1 = cVar1 + -1;
  } while ('\0' < cVar1);
  iRam000f0002 = param_3 + _DAT_2000_988e + (uint)in_CF;
  uRam000f0014 = 0x21;
  uRam000f0000 = 0x250f;
  uRam000f000e = 0x1c00;
  uRam000f0004 = param_1;
  uRam000f0006 = param_2;
  uRam000f0008 = param_5;
  uRam000f000a = param_6;
  uRam000f0010 = unaff_ES;
  fist_int_dispatch();
  DAT_0000_0598 = 0;
  DAT_0000_059a = 0;
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0772) @ 0000:0772 ===== */

undefined2 __allregs FUN_0000_0772(undefined2 param_1)

{
  DAT_0000_05a4 = DAT_0000_05a4 + 1;
  out(0x20,0x20);
  return param_1;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0826) @ 0000:0826 ===== */

undefined2 __allregs FUN_0000_0826(undefined1 param_1,undefined2 param_2,undefined2 *param_3)

{
  char cVar1;
  undefined2 *puVar2;
  undefined2 uStack_2;
  
  puVar2 = &uStack_2;
  cVar1 = '\x03';
  do {
    param_3 = param_3 + -1;
    puVar2 = puVar2 + -1;
    *puVar2 = *param_3;
    cVar1 = cVar1 + -1;
  } while ('\0' < cVar1);
  out(0x61,param_1);
  return param_2;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0833) @ 0000:0833 ===== */

void __allregs FUN_0000_0833(uint param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4)

{
  undefined2 uVar1;
  
  uVar1 = DAT_0000_0831;
  *(uint *)&DAT_1000_c012 = param_1;
  (*(code *)fist_icall(fist_snd_base+0x0u+(uint16_t)(*(undefined2 *)((param_1 >> 0xb & 0x1e) + 0x11b))))(param_2,param_3,param_4);
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_088f) @ 0000:088f ===== */

undefined2 __allregs FUN_0000_088f(int param_1,undefined2 param_2,undefined2 *param_3)

{
  byte bVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  undefined2 **ppuVar5;
  int iVar6;
  undefined2 *puStack_2;
  
  ppuVar5 = &puStack_2;
  cVar2 = '\x17';
  puStack_2 = param_3;
  do {
    param_3 = param_3 + -1;
    ppuVar5 = ppuVar5 + -1;
    *ppuVar5 = (undefined2 *)*param_3;
    cVar2 = cVar2 + -1;
  } while ('\0' < cVar2);
  bRam0001c862 = bRam0001c862 & (byte)((uint)param_2 >> 8);
  bRam0001c861 = bRam0001c861 ^ (byte)((uint)(param_1 + -0x4f44) >> 8);
  DAT_2000_c2f2 = DAT_2000_c2f2 & (byte)(param_1 + -0x4f44);
  bVar1 = *(byte *)&DAT_1000_c012;
  if ((bVar1 != 0) && (bVar1 < 6)) {
    *(byte *)&DAT_1000_c03e = bVar1;
    iVar3 = (uint)bVar1 * 2;
    *(undefined2 *)0x17b = *(undefined2 *)(iVar3 + 0x17d);
    *(undefined2 *)0x189 = *(undefined2 *)(iVar3 + 0x18b);
    *(undefined2 *)0x197 = *(undefined2 *)(iVar3 + 0x199);
    *(undefined2 *)&DAT_1000_c1a5 = *(undefined2 *)(iVar3 + 0x1a7);
    *(undefined2 *)0x1b3 = *(undefined2 *)(iVar3 + 0x1b5);
    *(undefined2 *)&DAT_1000_c1c1 = *(undefined2 *)(iVar3 + 0x1c3);
    *(undefined2 *)0x1cf = *(undefined2 *)(iVar3 + 0x1d1);
    *(undefined2 *)&DAT_1000_c010 = 0;
    iVar3 = (*(code *)fist_icall(fist_snd_base+0x0u+(uint16_t)(*(undefined2 *)0x17b)))();
    if (iVar3 != 0) {
      FUN_0000_0c94(iVar3);
      iVar4 = 0;
      iVar6 = 0;
      iVar3 = 10;
      do {
        *(undefined2 *)(iVar4 + 0x68) = 0xed3;
        *(undefined1 *)(iVar6 + 0xcc) = 0;
        *(undefined1 *)(iVar6 + 0x86) = 0;
        *(undefined1 *)(iVar6 + 0x111) = 0;
        *(undefined1 *)(iVar6 + 0x107) = 0;
        *(undefined2 *)(iVar4 + 0x90) = 0x15b0;
        *(undefined2 *)(iVar4 + 0xa4) = 0x15b0;
        iVar4 = iVar4 + 2;
        iVar6 = iVar6 + 1;
        iVar3 = iVar3 + -1;
      } while (iVar3 != 0);
      DAT_0000_05c2 = 0xa28;
      return 0xffff;
    }
  }
  DAT_0000_05c2 = 0x5c4;
  return 0;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0966) @ 0000:0966 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __allregs FUN_0000_0966(byte param_1,undefined2 param_2)

{
  _DAT_1000_d3e2 = 0x13e8;
  if (*(int *)(param_1 + 0x13e8) != 0) {
    FUN_0000_0997(param_1,param_2,0x983);
  }
  _DAT_1000_d3e2 = 0x13e4;
  FUN_0000_0997(param_1,param_2,0x993);
  return 0xffff;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0997) @ 0000:0997 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs FUN_0000_0997(byte param_1,int param_2,undefined2 param_3)

{
  char cVar1;
  byte bVar2;
  int iVar3;
  undefined1 *puVar4;
  
  iVar3 = (uint)DAT_1000_c03e << 3;
  cVar1 = '\b';
  do {
    bVar2 = *(byte *)(iVar3 + 0x13b);
    param_2 = CONCAT11(bVar2,(char)param_2);
    if (*(char *)(bVar2 + 0x107) == '\0') break;
    iVar3 = iVar3 + 1;
    cVar1 = cVar1 + -1;
  } while (cVar1 != '\0');
  puVar4 = (undefined1 *)((uint)param_1 * 8 + _DAT_1000_d3e2);
  *(undefined1 *)(bVar2 + 0x111) = *puVar4;
  FUN_0000_0cfb(puVar4[1],param_2);
  bVar2 = (char)((uint)_DAT_1000_c012 >> 8) << 4;
  if (bVar2 == 0) {
    bVar2 = 0xff;
  }
  iVar3 = (uint)*(byte *)(param_2 + 3) * (uint)bVar2;
  FUN_0000_0aa7(CONCAT11(*(undefined1 *)(param_2 + 2),(char)iVar3),
                CONCAT11((char)((uint)param_3 >> 8),(char)((uint)iVar3 >> 8)));
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0aa7) @ 0000:0aa7 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 __allregs FUN_0000_0aa7(undefined2 param_1,uint param_2)

{
  uint uVar1;
  char cVar2;
  
  uVar1 = param_2 >> 8;
  if ((_DAT_1000_c010 == 0) && (cVar2 = (char)((uint)param_1 >> 8), cVar2 != '\0')) {
    *(undefined2 *)(uVar1 * 2 + 0x90) = *(undefined2 *)(uVar1 * 2 + 0xa4);
    *(undefined1 *)(uVar1 + 0x107) = 1;
    *(char *)(uVar1 + 0xc2) = cVar2 + *(char *)(uVar1 + 0xd6);
    *(undefined1 *)(uVar1 + 0xcc) = 0xff;
                    /* WARNING: Could not recover jumptable at 0x00000ae2. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c1a5)))();
    return;
  }
  *(undefined1 *)(uVar1 + 0x107) = 0;
                    /* WARNING: Could not recover jumptable at 0x00000aec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c1a5)))();
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0af0) @ 0000:0af0 ===== */

void __allregs FUN_0000_0af0(undefined2 param_1,undefined2 param_2)

{
  FUN_0000_0af4(param_1,param_2);
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0af4) @ 0000:0af4 ===== */

void __allregs FUN_0000_0af4(uint param_1,int param_2)

{
  undefined2 uVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  undefined1 *puVar5;
  undefined2 unaff_ES;
  
  uVar1 = DAT_0000_0831;
  if (((param_1 & 1) != 0) && (*(int *)&DAT_1000_c00e != 0)) {
    *(uint *)&DAT_1000_c004 = param_1;
    *(undefined2 *)0x0 = unaff_ES;
    *(int *)&DAT_1000_c002 = param_2;
    return;
  }
  *(uint *)&DAT_1000_c00a = param_1;
  *(int *)&DAT_1000_c008 = param_2;
  *(undefined2 *)&DAT_1000_c006 = unaff_ES;
  puVar5 = (undefined1 *)(param_2 + 0x10);
  iVar3 = 0;
  iVar2 = 0x10;
  do {
    param_1 = CONCAT11((char)(param_1 >> 8),*puVar5);
    *(undefined1 *)(iVar3 + 0x20) = *puVar5;
    iVar3 = iVar3 + 1;
    puVar5 = puVar5 + 1;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  uVar4 = 0;
  do {
    param_1 = CONCAT11((char)(param_1 >> 8),*puVar5);
    *(undefined1 *)(uVar4 + 0x2a) = *puVar5;
    *(undefined1 *)(uVar4 + 0x34) = 0xff;
    puVar5 = puVar5 + 1;
    uVar4 = uVar4 + 1;
  } while (uVar4 < 0x10);
  *(undefined2 *)&DAT_1000_c00c = puVar5;
  FUN_0000_0c94(param_1);
  *(undefined2 *)&DAT_1000_c014 = 1;
  *(undefined2 *)&DAT_1000_c00e = 0xffff;
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0b80) @ 0000:0b80 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 __allregs
FUN_0000_0b80(undefined2 param_1,char param_2,int param_3,int param_4,undefined2 *param_5,
             int param_6)

{
  char cVar1;
  undefined1 uVar2;
  undefined1 in_CH;
  char *pcVar3;
  undefined2 **ppuVar4;
  undefined2 *puStack_2;
  
  ppuVar4 = &puStack_2;
  cVar1 = '\x0f';
  puStack_2 = param_5;
  do {
    param_5 = param_5 + -1;
    ppuVar4 = ppuVar4 + -1;
    *ppuVar4 = (undefined2 *)*param_5;
    cVar1 = cVar1 + -1;
  } while ('\0' < cVar1);
  uVar2 = (undefined1)((uint)param_1 >> 8);
  if (param_2 == -0x70) {
    *(undefined1 *)(param_4 + 0x16) = uVar2;
    param_6 = param_3 + 1;
  }
  else {
    if (param_2 == -0x80) {
      *(undefined1 *)(param_4 + 0x16) = 0;
      pcVar3 = (char *)(param_3 + 1);
      goto LAB_0000_0bd3;
    }
    if (param_2 == -0x40) {
      FUN_0000_0cf3(uVar2,CONCAT11(in_CH,param_2));
    }
    else {
      param_6 = param_3;
      if (param_2 != -0x30) {
        if (param_2 == -0x20) {
          *(undefined1 *)(param_4 + 0xb8) = uVar2;
        }
        else if (param_2 == -0x50) {
          param_6 = param_3 + 1;
        }
      }
    }
  }
  pcVar3 = (char *)(param_6 + 2);
LAB_0000_0bd3:
  if (*pcVar3 < '\0') {
    pcVar3 = pcVar3 + 1;
  }
  _DAT_1000_c00c = pcVar3 + 1;
  return 1;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0bf7) @ 0000:0bf7 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs FUN_0000_0bf7(undefined2 param_1)

{
  uint uVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  undefined2 uVar5;
  
  _DAT_1000_c014 = 1;
  FUN_0000_0ca9(param_1,0xc00);
  uVar1 = _DAT_1000_c004;
  _DAT_1000_c00e = 0;
  if ((_DAT_1000_c004 & 1) == 0) {
    uVar5 = _DAT_1000_c006;
    if ((_DAT_1000_c00a & 2) == 0) {
      return;
    }
  }
  else {
    _DAT_1000_c004 = 0;
    _DAT_1000_c00a = uVar1;
    _DAT_1000_c008 = _DAT_1000_c002;
    uVar5 = _DAT_1000_c000;
  }
  _DAT_1000_c00c = (undefined1 *)(_DAT_1000_c008 + 0x10);
  iVar3 = 0;
  iVar2 = 0x10;
  uVar1 = _DAT_1000_c00a;
  _DAT_1000_c006 = uVar5;
  do {
    uVar1 = CONCAT11((char)(uVar1 >> 8),*_DAT_1000_c00c);
    *(undefined1 *)(iVar3 + 0x20) = *_DAT_1000_c00c;
    iVar3 = iVar3 + 1;
    _DAT_1000_c00c = _DAT_1000_c00c + 1;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  uVar4 = 0;
  do {
    uVar1 = CONCAT11((char)(uVar1 >> 8),*_DAT_1000_c00c);
    *(undefined1 *)(uVar4 + 0x2a) = *_DAT_1000_c00c;
    *(undefined1 *)(uVar4 + 0x34) = 0xff;
    _DAT_1000_c00c = _DAT_1000_c00c + 1;
    uVar4 = uVar4 + 1;
  } while (uVar4 < 0x10);
  FUN_0000_0c94(uVar1);
  _DAT_1000_c014 = 1;
  _DAT_1000_c00e = 0xffff;
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0c94) @ 0000:0c94 ===== */

void __allregs FUN_0000_0c94(undefined2 param_1)

{
  undefined2 uVar1;
  
  uVar1 = DAT_0000_0831;
  *(undefined2 *)&DAT_1000_c00e = 0;
  *(undefined2 *)&DAT_1000_c004 = 0;
  FUN_0000_0ca9(param_1,0xca8);
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0ca9) @ 0000:0ca9 ===== */

void __allregs FUN_0000_0ca9(uint param_1,undefined2 param_2)

{
  undefined2 uVar1;
  int iVar2;
  char cVar3;
  int iVar4;
  
  uVar1 = DAT_0000_0831;
  iVar4 = 0;
  iVar2 = 0;
  do {
    cVar3 = (char)((uint)iVar2 >> 8);
    param_1 = param_1 & 0xff;
    *(undefined1 *)(iVar4 + 0xb8) = 0;
    if (*(char *)(iVar4 + 0x111) == '\0') {
      param_1 = FUN_0000_0aa7(param_1,iVar2);
      cVar3 = (char)((uint)param_2 >> 8);
      iVar4 = iVar2;
    }
    iVar2 = (uint)(byte)(cVar3 + 1U) << 8;
    iVar4 = iVar4 + 1;
  } while ((byte)(cVar3 + 1U) < 10);
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0cd1) @ 0000:0cd1 ===== */

/* WARNING (jumptable): Stack frame is not setup normally: Input value of stackpointer is not used
    */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __allregs
FUN_0000_0cd1(byte param_1,byte param_2,int param_3,int param_4,int param_5,undefined2 *param_6,
             undefined1 *param_7)

{
  byte *pbVar1;
  undefined1 uVar2;
  byte bVar3;
  uint uVar4;
  undefined2 uVar5;
  uint uVar6;
  int iVar7;
  int iVar8;
  undefined2 *puVar9;
  undefined2 *puVar10;
  undefined4 in_ESP;
  undefined2 *puVar11;
  undefined2 unaff_ES;
  undefined2 in_GS;
  
  param_7[0x53] = param_7[0x53] & param_2;
  puVar9 = (undefined2 *)((uint)in_ESP ^ *(uint *)(param_4 + (int)param_6));
  out(*param_6,param_3);
  if (!SCARRY2(param_4,1)) {
    puVar11 = (undefined2 *)CONCAT22((int)((ulong)in_ESP >> 0x10),puVar9) + -1;
    *puVar11 = 0x2074;
    *(uint *)(param_7 + param_4 + 1) = *(uint *)(param_7 + param_4 + 1) ^ (uint)param_7;
    param_7[param_5 + 0x79] = param_7[param_5 + 0x79] & param_2;
    uVar2 = in(param_3);
    *param_7 = uVar2;
    *(byte *)(param_5 + 0x72) = *(byte *)(param_5 + 0x72) & param_1;
    uVar5 = in(param_3);
    *(undefined2 *)(param_7 + 1) = uVar5;
    puVar10 = (undefined2 *)puVar11;
    uVar5 = puVar10[6];
    uVar4 = puVar10[7];
    out(*(undefined1 *)puVar10[1],puVar10[5]);
    pbVar1 = (undefined1 *)puVar10[1] + puVar10[4] + 1;
    *pbVar1 = *pbVar1 & (byte)(uVar4 >> 8);
    *(undefined1 *)((byte)((uint)uVar5 >> 8) + 0x2a) = (char)uVar4;
    uVar6 = (uint)(byte)((uint)uVar5 >> 8);
    iVar7 = uVar6 * 2;
    *(undefined1 *)(uVar6 + 0x34) = (char)uVar4;
    iVar8 = (uVar4 & 0xff) * 2;
    uVar5 = *(undefined2 *)(iVar8 + 0x15b4);
    *(undefined2 *)(iVar7 + 0xa4) = uVar5;
    *(undefined2 *)(iVar7 + 0x90) = uVar5;
    *(undefined2 *)(iVar7 + 0x40) = *(undefined2 *)(iVar8 + 0xfc9);
    *(undefined2 *)(iVar7 + 0x54) = *(undefined2 *)(iVar8 + 0x10d4);
    *(undefined1 *)(uVar6 + 0xfd) = *(undefined1 *)((uVar4 & 0xff) + 0x152e);
    *(undefined1 *)(uVar6 + 0xd6) = *(undefined1 *)((uVar4 & 0xff) + 0x14ac);
                    /* WARNING: Could not recover jumptable at 0x00000d45. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    uVar5 = (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c1c1)))();
    return uVar5;
  }
  do {
    bVar3 = in(param_3);
  } while ((bVar3 & 0x40) != 0);
  uVar5 = *puVar9;
  out(param_3 + -1,(char)uVar5);
  return uVar5;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0cf3) @ 0000:0cf3 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs FUN_0000_0cf3(byte param_1,undefined2 param_2)

{
  undefined2 uVar1;
  byte bVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  
  bVar2 = (byte)((uint)param_2 >> 8);
  *(byte *)(bVar2 + 0x2a) = param_1;
  uVar3 = (uint)bVar2;
  iVar4 = uVar3 * 2;
  uVar5 = (uint)param_1;
  *(byte *)(uVar3 + 0x34) = param_1;
  iVar6 = uVar5 * 2;
  uVar1 = *(undefined2 *)(iVar6 + 0x15b4);
  *(undefined2 *)(iVar4 + 0xa4) = uVar1;
  *(undefined2 *)(iVar4 + 0x90) = uVar1;
  *(undefined2 *)(iVar4 + 0x40) = *(undefined2 *)(iVar6 + 0xfc9);
  *(undefined2 *)(iVar4 + 0x54) = *(undefined2 *)(iVar6 + 0x10d4);
  *(undefined1 *)(uVar3 + 0xfd) = *(undefined1 *)(uVar5 + 0x152e);
  *(undefined1 *)(uVar3 + 0xd6) = *(undefined1 *)(uVar5 + 0x14ac);
                    /* WARNING: Could not recover jumptable at 0x00000d45. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c1c1)))();
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0cfb) @ 0000:0cfb ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __allregs FUN_0000_0cfb(byte param_1,uint param_2)

{
  undefined2 uVar1;
  uint uVar2;
  int iVar3;
  uint uVar4;
  int iVar5;
  
  uVar2 = param_2 >> 8;
  iVar3 = uVar2 * 2;
  uVar4 = (uint)param_1;
  *(byte *)(uVar2 + 0x34) = param_1;
  iVar5 = uVar4 * 2;
  uVar1 = *(undefined2 *)(iVar5 + 0x15b4);
  *(undefined2 *)(iVar3 + 0xa4) = uVar1;
  *(undefined2 *)(iVar3 + 0x90) = uVar1;
  *(undefined2 *)(iVar3 + 0x40) = *(undefined2 *)(iVar5 + 0xfc9);
  *(undefined2 *)(iVar3 + 0x54) = *(undefined2 *)(iVar5 + 0x10d4);
  *(undefined1 *)(uVar2 + 0xfd) = *(undefined1 *)(uVar4 + 0x152e);
  *(undefined1 *)(uVar2 + 0xd6) = *(undefined1 *)(uVar4 + 0x14ac);
                    /* WARNING: Could not recover jumptable at 0x00000d45. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)fist_icall_far((uint32_t)(_DAT_1000_c1c1)))();
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0d49) @ 0000:0d49 ===== */

undefined2 __allregs FUN_0000_0d49(undefined2 param_1)

{
  byte bVar1;
  
  do {
    bVar1 = in(0x331);
  } while ((bVar1 & 0x40) != 0);
  out(0x330,(char)param_1);
  return param_1;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0d66) @ 0000:0d66 ===== */

undefined4 __allregs FUN_0000_0d66(void)

{
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0d67) @ 0000:0d67 ===== */

undefined1 __allregs FUN_0000_0d67(undefined1 param_1)

{
  byte bVar1;
  undefined1 uVar2;
  
  do {
    bVar1 = in(0x331);
  } while ((bVar1 & 0x40) != 0);
  out(0x331,param_1);
  do {
    bVar1 = in(0x331);
  } while ((bVar1 & 0x80) != 0);
  uVar2 = in(0x330);
  return uVar2;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0d90) @ 0000:0d90 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 __allregs FUN_0000_0d90(undefined1 param_1)

{
  byte bVar1;
  undefined1 uVar2;
  int iVar3;
  
  iVar3 = _DAT_1000_cc31;
  while( true ) {
    in(0x331);
    bVar1 = in(0x331);
    if ((bVar1 & 0x40) == 0) break;
    iVar3 = iVar3 + -1;
    if (iVar3 == 0) {
      return 0;
    }
  }
  out(0x331,param_1);
  iVar3 = _DAT_1000_cc31;
  do {
    in(0x331);
    bVar1 = in(0x331);
    if ((bVar1 & 0x80) == 0) break;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  uVar2 = in(0x330);
  return uVar2;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0dc9) @ 0000:0dc9 ===== */

void __allregs FUN_0000_0dc9(void)

{
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0e94) @ 0000:0e94 ===== */

/* WARNING: Instruction at (ram,0x00000e95) overlaps instruction at (ram,0x00000e94)
    */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

ulong __allregs
FUN_0000_0e94(uint param_1,int param_2,int param_3,undefined2 *param_4,int param_5,uint *param_6)

{
  char *pcVar1;
  char cVar2;
  undefined1 uVar3;
  undefined2 uVar4;
  uint uVar5;
  undefined4 uVar6;
  ulong uVar7;
  undefined3 uVar8;
  undefined3 extraout_var;
  int iVar9;
  int iVar10;
  byte bVar11;
  byte bVar12;
  undefined2 **ppuVar13;
  undefined2 unaff_ES;
  undefined2 *puStack_2;
  
  uVar7 = (ulong)param_1;
  ppuVar13 = &puStack_2;
  cVar2 = '\x0f';
  puStack_2 = param_4;
  do {
    param_4 = param_4 + -1;
    ppuVar13 = ppuVar13 + -1;
    *ppuVar13 = (undefined2 *)*param_4;
    cVar2 = cVar2 + -1;
  } while ('\0' < cVar2);
  pcVar1 = (char *)(param_3 + param_5 + -0x1785);
  *pcVar1 = *pcVar1 + '\x01';
  *param_6 = param_1;
  pcVar1 = (char *)(param_3 + param_5 + -0x1800);
  *pcVar1 = *pcVar1 + '\x01';
  pcVar1 = (char *)((int)param_6 + param_3 + -0x1b);
  *pcVar1 = *pcVar1 + '\x01';
  iVar9 = param_2 + -1;
  iVar10 = 0;
  if (iVar9 != 0) {
    while( true ) {
      uVar4 = FUN_0000_0d49((int)uVar7);
      uVar5 = FUN_0000_0d49((int)CONCAT31((uint3)(byte)((uint)uVar4 >> 8),0x7b));
      FUN_0000_0d49(uVar5 & 0xff00);
      iVar9 = iVar9 + -1;
      if (iVar9 == 0) break;
      uVar6 = FUN_0000_0d66();
      (*(undefined1 *)((char *)&param_1 + 0)) = (char)iVar9 + -0x51;
      uVar7 = CONCAT31((int3)((ulong)uVar6 >> 8),(char)param_1);
    }
    iVar10 = DAT_0000_05a6 << 1;
  }
  DAT_1000_ce8b = DAT_1000_ce8b + (char)((uint)iVar10 >> 8);
  iVar10 = iVar10 << 4;
  _DAT_1000_cc31 = iVar10;
  uVar7 = FUN_0000_0d66();
  iVar9 = 0;
  do {
    while( true ) {
      bVar12 = (byte)((uint)iVar10 >> 8);
      cVar2 = *(char *)(iVar9 + 0xc33);
      uVar8 = (undefined3)(uVar7 >> 8);
      uVar7 = CONCAT31(uVar8,cVar2);
      uVar5 = (uint)uVar7;
      if (cVar2 == -1) {
        uVar3 = FUN_0000_0d90(0x3f);
        return CONCAT31(extraout_var,uVar3);
      }
      if (cVar2 != -3) break;
      bVar11 = bVar12 & 0x7f;
      bVar12 = -bVar11 & 0x7f;
      uVar5 = (uint)CONCAT31(uVar8,-bVar11) & 0xff7f;
LAB_0000_0ee4:
      iVar10 = (uint)(byte)(bVar12 + (char)uVar5) << 8;
      uVar5 = FUN_0000_0d49(uVar5);
      uVar7 = (ulong)uVar5;
      iVar9 = iVar9 + 1;
    }
    if (cVar2 != -4) goto LAB_0000_0ee4;
    iVar10 = 0;
    iVar9 = iVar9 + 1;
  } while( true );
}


/* ===== ((uint)(uintptr_t)&FUN_0000_0ef5) @ 0000:0ef5 ===== */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __allregs FUN_0000_0ef5(void)

{
  char cVar1;
  
  _DAT_1000_cc31 = DAT_0000_05a6 << 5;
  cVar1 = FUN_0000_0d90(0xff);
  if (cVar1 != -2) {
    cVar1 = FUN_0000_0d90(0xff);
    if (cVar1 != -2) {
      return 0;
    }
  }
  return 0xffff;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_1b3c) @ 0000:1b3c ===== */

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */
/* WARNING: Removing unreachable block (ram,0x00001cb1) */

uint __allregs
FUN_0000_1b3c(int param_1,undefined2 param_2,undefined2 param_3,int param_4,int param_5,
             undefined2 param_6,uint param_7)

{
  byte *pbVar1;
  char *pcVar2;
  undefined1 uVar3;
  byte bVar4;
  code *pcVar5;
  byte bVar6;
  undefined2 uVar7;
  undefined2 *puVar8;
  undefined2 uVar9;
  undefined2 uVar10;
  undefined2 uVar11;
  byte bVar12;
  byte bVar13;
  int iVar14;
  byte bVar16;
  uint uVar15;
  byte bVar17;
  byte bVar19;
  undefined2 uVar18;
  byte bVar20;
  int iVar21;
  undefined4 *puVar22;
  int iVar23;
  undefined4 in_ESP;
  undefined4 *puVar24;
  byte *pbVar25;
  undefined1 *puVar26;
  int iVar27;
  undefined2 *puVar28;
  undefined2 unaff_ES;
  undefined2 uVar29;
  undefined2 unaff_CS;
  undefined2 uVar30;
  undefined2 uVar31;
  undefined2 uVar32;
  bool bVar33;
  bool bVar34;
  bool bVar35;
  byte bVar36;
  char cVar37;
  byte in_AF;
  char cVar38;
  char cVar39;
  char cVar40;
  
  iVar14 = param_1 + 1;
  iVar23 = (int)in_ESP;
  *(int *)(iVar23 + -2) = iVar14;
  *(undefined2 *)(iVar23 + -4) = param_2;
  *(undefined2 *)(iVar23 + -6) = param_3;
  *(int *)(iVar23 + -8) = param_4;
  *(int *)(iVar23 + -10) = iVar23;
  *(int *)(iVar23 + -0xc) = param_5;
  *(undefined2 *)(iVar23 + -0xe) = param_6;
  *(uint *)(iVar23 + -0x10) = param_7;
  if (!SCARRY2(param_1,1)) {
    if (param_1 < -1) goto LAB_0000_1bc0;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
    *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
  }
  *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
  *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
  *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
  *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
LAB_0000_1bc0:
  *(int *)(param_4 + param_7) = *(int *)(param_4 + param_7) + iVar14;
  *(char *)(param_4 + param_7) = *(char *)(param_4 + param_7) + (char)iVar14;
  cVar37 = *(char *)(param_5 + param_7);
  bVar16 = (byte)((uint)iVar14 >> 8);
  *(undefined2 *)(iVar23 + -0x12) = unaff_ES;
  uVar29 = *(undefined2 *)(iVar23 + -0x12);
  *(byte *)(param_4 + param_7) = *(byte *)(param_4 + param_7) | (byte)param_2;
  bVar36 = *(byte *)(param_5 + param_7);
  cVar39 = (char)((uint)param_2 >> 8);
  bVar12 = (char)iVar14 + cVar37 + 5U | 0xd;
  *(undefined2 *)(iVar23 + -0x12) = unaff_CS;
  bVar17 = (byte)param_3;
  bVar33 = CARRY1(bVar17,*(byte *)(param_5 + param_7));
  bVar4 = *(byte *)(param_5 + param_7);
  bVar19 = (byte)((uint)param_3 >> 8);
  bVar6 = bVar12 + 0x15;
  bVar34 = 0xea < bVar12 || CARRY1(bVar6,bVar33);
  *(undefined2 *)(iVar23 + -0x14) = 0x2ba9;
  uVar30 = *(undefined2 *)(iVar23 + -0x14);
  pbVar1 = (byte *)(param_4 + param_7);
  bVar20 = (byte)param_4;
  bVar35 = *pbVar1 < bVar20 || (byte)(*pbVar1 - bVar20) < bVar34;
  *pbVar1 = (*pbVar1 - bVar20) - bVar34;
  bVar12 = *(byte *)(param_5 + param_7);
  bVar13 = bVar20 - *(byte *)(param_5 + param_7);
  iVar14 = CONCAT11((char)((uint)param_4 >> 8),bVar13 - bVar35);
  *(undefined2 *)(iVar23 + -0x14) = 0x1c00;
  uVar32 = *(undefined2 *)(iVar23 + -0x14);
  *(byte *)(iVar14 + param_7) = *(byte *)(iVar14 + param_7) & bVar16;
  uVar15 = CONCAT11(bVar16 & *(byte *)(param_5 + param_7),
                    (bVar6 + bVar33 + -0x1d) - (bVar20 < bVar12 || bVar13 < bVar35)) & 0xff25;
  bVar12 = (byte)uVar15;
  bVar6 = 9 < (bVar12 & 0xf) | in_AF;
  *(char *)(iVar14 + param_7) = *(char *)(iVar14 + param_7) - cVar39;
  cVar37 = *(char *)(param_5 + param_7);
  bVar13 = (bVar12 + bVar6 * '\x06') - 0x2d;
  bVar6 = 9 < (bVar13 & 0xf) | bVar6;
  *(byte *)(iVar14 + param_7) = *(byte *)(iVar14 + param_7) ^ bVar19;
  bVar12 = *(byte *)(param_5 + param_7);
  bVar13 = bVar13 + bVar6 * -6 ^ 0x35;
  bVar6 = 9 < (bVar13 & 0xf) | bVar6;
  bVar13 = bVar13 + bVar6 * '\x06' & 0xf;
  cVar38 = 9 < bVar13 | bVar6;
  iVar27 = param_7 + 1;
  *(uint *)(iVar23 + -0x14) =
       CONCAT11(((char)(uVar15 >> 8) + bVar6) - cVar38,bVar13 + cVar38 * -6) & 0xff0f;
  *(undefined2 *)(iVar23 + -0x16) = CONCAT11(cVar39 - cVar37,(byte)param_2 | bVar36);
  *(undefined2 *)(iVar23 + -0x18) = CONCAT11(bVar19 ^ bVar12,bVar17 + bVar4);
  *(int *)(iVar23 + -0x1a) = iVar14;
  *(int *)(iVar23 + -0x1c) = iVar23 + -0x1a;
  *(int *)(iVar23 + -0x1e) = param_5;
  *(undefined2 *)(iVar23 + -0x20) = param_6;
  *(uint *)(iVar23 + -0x22) = param_7;
  uVar31 = *(undefined2 *)(iVar23 + -0x20);
  uVar18 = *(undefined2 *)(iVar23 + -0x1e);
  uVar7 = *(undefined2 *)(iVar23 + -0x1c);
  puVar8 = (undefined2 *)*(undefined2 *)(iVar23 + -0x1a);
  uVar9 = *puVar8;
  uVar10 = puVar8[1];
  uVar11 = puVar8[2];
  puVar8[2] = *(undefined2 *)(iVar23 + -0x22);
  puVar8[1] = uVar31;
  *puVar8 = uVar18;
  puVar8[-1] = uVar7;
  puVar8[-2] = puVar8 + 3;
  puVar8[-3] = uVar9;
  puVar8[-4] = uVar10;
  puVar8[-5] = uVar11;
  puVar28 = (undefined2 *)puVar8[-5];
  puVar26 = (undefined1 *)puVar8[-4];
  pbVar25 = (byte *)puVar8[-3];
  iVar21 = puVar8[-1];
  uVar18 = *puVar8;
  iVar14 = puVar8[1];
  uVar15 = puVar8[2];
  puVar24 = (undefined4 *)((undefined2 *)CONCAT22((int)((ulong)in_ESP >> 0x10),puVar8 + 3) + -2);
  *puVar24 = 0x6c6b6a69;
  uVar31 = in(uVar18);
  *puVar28 = uVar31;
  out(*puVar26,uVar18);
  out(*(undefined2 *)(puVar26 + 1),uVar18);
  if (SBORROW2(iVar27,1)) {
    if (iVar14 == 0) {
      return uVar15;
    }
    uVar15 = in(0xe6);
  }
  else if (!(bool)cVar38) {
    if (param_7 == 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    if ((int)param_7 < 0) {
      do {
                    /* WARNING: Do nothing block with infinite loop */
      } while( true );
    }
    if (((POPCOUNT(param_7 & 0xff) & 1U) != 0) && (0 < iVar27)) {
      if (0 < iVar27) {
        pcVar2 = (char *)((int)puVar28 + iVar21 + -0x7c7c);
        *pcVar2 = *pcVar2 + -0x7c;
        bVar36 = 0;
        uVar15 = *(uint *)(pbVar25 + -0x7779) & uVar15;
        cVar40 = (int)uVar15 < 0;
        cVar39 = uVar15 == 0;
        cVar37 = (POPCOUNT(uVar15 & 0xff) & 1U) == 0;
        *(int *)(pbVar25 + (int)puVar26 + -0x7372) = iVar14;
        *(undefined2 *)(iVar21 + -2) = unaff_CS;
        *(undefined2 *)(iVar21 + -4) = 0x1c61;
        func_0x000a866b();
        uVar3 = *(undefined1 *)&DAT_2000_62a1;
        uVar31 = CONCAT11(cVar40 << 7 | cVar39 << 6 | cVar38 << 4 | cVar37 << 2 | 2U | bVar36,uVar3)
        ;
        *(undefined2 *)&DAT_2000_65a4 = uVar31;
        puVar26[6] = uVar3;
        *(undefined2 *)(puVar26 + 7) = uVar31;
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  out(0xe8,uVar15);
  puVar22 = (undefined4 *)puVar24;
  *(int *)((int)puVar22 + -2) = uVar15 + 0xb0bd;
  *(undefined2 *)((int)puVar22 + -2) = uVar18;
  *(undefined2 **)(puVar22 + -1) = (undefined2 *)((int)puVar22 + -2);
  pbVar25[1] = pbVar25[1] & (byte)((uint)uVar18 >> 8);
  *pbVar25 = *pbVar25 ^ (byte)(uVar15 + 0xb0bc >> 8);
  pbVar25[1] = pbVar25[1] & (byte)(uVar15 + 0xb0bc);
  uVar31 = *(undefined2 *)puVar22;
  bVar36 = *(byte *)&DAT_1000_c012;
  if ((bVar36 != 0) && (bVar36 < 6)) {
    *(byte *)&DAT_1000_c03e = bVar36;
    iVar14 = (uint)bVar36 * 2;
    *(undefined2 *)0x17b = *(undefined2 *)(iVar14 + 0x17d);
    *(undefined2 *)0x189 = *(undefined2 *)(iVar14 + 0x18b);
    *(undefined2 *)0x197 = *(undefined2 *)(iVar14 + 0x199);
    *(undefined2 *)&DAT_1000_c1a5 = *(undefined2 *)(iVar14 + 0x1a7);
    *(undefined2 *)0x1b3 = *(undefined2 *)(iVar14 + 0x1b5);
    *(undefined2 *)&DAT_1000_c1c1 = *(undefined2 *)(iVar14 + 0x1c3);
    *(undefined2 *)0x1cf = *(undefined2 *)(iVar14 + 0x1d1);
    *(undefined2 *)&DAT_1000_c010 = 0;
    pcVar5 = (code *)*(undefined2 *)0x17b;
    *(undefined2 *)puVar22 = 0x91d;
    iVar14 = (*pcVar5)();
    if (iVar14 != 0) {
      *(undefined2 *)((int)puVar22 + -2) = 0x924;
      FUN_0000_0c94(iVar14);
      iVar21 = 0;
      iVar27 = 0;
      iVar14 = 10;
      do {
        *(undefined2 *)(iVar21 + 0x68) = 0xed3;
        *(undefined1 *)(iVar27 + 0xcc) = 0;
        *(undefined1 *)(iVar27 + 0x86) = 0;
        *(undefined1 *)(iVar27 + 0x111) = 0;
        *(undefined1 *)(iVar27 + 0x107) = 0;
        *(undefined2 *)(iVar21 + 0x90) = 0x15b0;
        *(undefined2 *)(iVar21 + 0xa4) = 0x15b0;
        iVar21 = iVar21 + 2;
        iVar27 = iVar27 + 1;
        iVar14 = iVar14 + -1;
      } while (iVar14 != 0);
      DAT_0000_05c2 = 0xa28;
      return 0xffff;
    }
  }
  DAT_0000_05c2 = 0x5c4;
  return 0;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_1c8f) @ 0000:1c8f ===== */

/* WARNING: Removing unreachable block (ram,0x00001c8f) */

undefined2 __allregs
FUN_0000_1c8f(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,
             undefined2 param_5,undefined2 param_6,undefined2 param_7)

{
  undefined2 unaff_ES;
  
  uRam000f0014 = 0xce;
  uRam000f000e = 0x1c00;
  uRam000f0000 = param_1;
  uRam000f0002 = param_4;
  uRam000f0004 = param_2;
  uRam000f0006 = param_3;
  uRam000f0008 = param_6;
  uRam000f000a = param_7;
  uRam000f000c = param_5;
  uRam000f0010 = unaff_ES;
  fist_int_dispatch();
  return uRam000f0000;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_216b) @ 0000:216b ===== */

undefined2 __allregs FUN_0000_216b(undefined2 param_1)

{
  undefined1 uVar1;
  undefined2 uVar2;
  int iVar3;
  
  out(0x388,(char)((uint)param_1 >> 8));
  iVar3 = 4;
  do {
    uVar1 = in(0x388);
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  uVar2 = CONCAT11(uVar1,(char)param_1);
  out(0x389,(char)param_1);
  iVar3 = 0x17;
  do {
    uVar1 = in(0x388);
    uVar2 = CONCAT11((char)((uint)uVar2 >> 8),uVar1);
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return uVar2;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_2187) @ 0000:2187 ===== */

undefined2 __allregs FUN_0000_2187(void)

{
  undefined1 in_ZF = 0;
  
  FUN_0000_2196();
  if (!(bool)in_ZF) {
    return 0;
  }
  return 0xffff;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_2196) @ 0000:2196 ===== */

void __allregs FUN_0000_2196(void)

{
  int iVar1;
  int iVar2;
  undefined2 uVar3;
  
  uVar3 = 0x388;
  FUN_0000_216b(0x460);
  FUN_0000_216b(0x480);
  in(uVar3);
  FUN_0000_216b(0x2ff);
  FUN_0000_216b(0x421);
  iVar2 = 0x13;
  iVar1 = DAT_0000_05a6;
  do {
    do {
      iVar1 = iVar1 + -1;
    } while (iVar1 != 0);
    iVar2 = iVar2 + -1;
    iVar1 = DAT_0000_05a6;
  } while (iVar2 != 0);
  in(uVar3);
  FUN_0000_216b(0x460);
  FUN_0000_216b(0x480);
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_224c) @ 0000:224c ===== */

/* WARNING: Instruction at (ram,0x0000224d) overlaps instruction at (ram,0x0000224c)
    */

uint __allregs FUN_0000_224c(int param_1,int param_2,undefined2 *param_3)

{
  char cVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  undefined2 uVar4;
  uint uVar5;
  undefined2 **ppuVar6;
  undefined2 *puStack_2;
  
  ppuVar6 = &puStack_2;
  cVar1 = '\t';
  puStack_2 = param_3;
  do {
    param_3 = param_3 + -1;
    ppuVar6 = ppuVar6 + -1;
    *ppuVar6 = (undefined2 *)*param_3;
    cVar1 = cVar1 + -1;
  } while ('\0' < cVar1);
  while( true ) {
    func_0x0000fc4a();
    if (0x951 < (uint)(param_1 + param_2)) break;
    out(0x43,0x80);
    uVar3 = in(0x42);
    uVar2 = in(0x42);
    param_1 = -CONCAT11(uVar2,uVar3);
  }
  FUN_0000_216b(0xb020);
  FUN_0000_216b(0xa000);
  uVar4 = FUN_0000_216b(0x4020);
  uVar3 = in(0x61);
  uVar5 = CONCAT11((char)((uint)uVar4 >> 8),uVar3) & 0xfffc;
  out(0x61,(char)uVar5);
  return uVar5;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_2278) @ 0000:2278 ===== */

void __allregs FUN_0000_2278(void)

{
  FUN_0000_216b(0x120);
  FUN_0000_216b(0x800);
  FUN_0000_216b(0xbdc0);
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_25eb) @ 0000:25eb ===== */

/* WARNING: Instruction at (ram,0x000025f1) overlaps instruction at (ram,0x000025f0)
    */
/* WARNING: Removing unreachable block (ram,0x000025f0) */
/* WARNING: Removing unreachable block (ram,0x000025f2) */

void __allregs FUN_0000_25eb(int param_1)

{
  bool in_SF;
  
  if (!in_SF) {
    param_1 = param_1 << 1;
  }
  iRam000025ec = *(int *)(param_1 + 8);
  iRam000025ee = iRam000025ec + 1;
  iRam000025f0 = iRam000025ec + 2;
  return;
}


/* ===== ((uint)(uintptr_t)&FUN_0000_386d) @ 0000:386d ===== */

/* WARNING: Control flow encountered bad instruction data */

void __allregs
FUN_0000_386d(undefined2 param_1,int param_2,undefined2 param_3,undefined2 param_4,
             undefined2 *param_5,int param_6,char *param_7)

{
  int *piVar1;
  char *pcVar2;
  int iVar3;
  char cVar4;
  uint uVar5;
  char cVar6;
  char cVar7;
  int iVar8;
  char cVar9;
  char cVar10;
  char cVar11;
  int iVar12;
  undefined2 **ppuVar14;
  int iVar15;
  undefined2 in_FS;
  undefined1 auStack_4 [2];
  undefined2 *puStack_2;
  char cVar13;
  
  ppuVar14 = &puStack_2;
  puStack_2 = param_5;
  cVar4 = '\x01';
  do {
    param_5 = param_5 + -1;
    ppuVar14 = ppuVar14 + -1;
    *ppuVar14 = (undefined2 *)*param_5;
    cVar4 = cVar4 + -1;
  } while ('\0' < cVar4);
  uVar5 = CONCAT11((char)((uint)param_1 >> 8),DAT_2000_4d02 + param_7[2]) ^ 0x2502;
  cVar10 = (char)((uint)param_3 >> 8);
  cVar9 = (char)param_3 + *param_7;
  iVar8 = (int)&puStack_2 + param_2;
  iVar12 = CONCAT11((char)((uint)param_4 >> 8) + (&stack0x0000)[param_6],(char)param_4) * 2;
  iVar15 = (int)&puStack_2 + iVar8;
  iVar3 = CONCAT11((char)(uVar5 >> 8),(char)uVar5 + DAT_2000_b702) * 2;
  *(int *)(param_7 + iVar15 + -0x58ff) = *(int *)(param_7 + iVar15 + -0x58ff) + param_6;
  *(int *)(param_7 + iVar15 + -0x70ff) = *(int *)(param_7 + iVar15 + -0x70ff) + iVar12;
  *(int *)(param_6 + 0x7901) = *(int *)(param_6 + 0x7901) + iVar3;
  piVar1 = (int *)((int)&puStack_2 + iVar8 + 1);
  *piVar1 = *piVar1 + iVar15;
  *(int *)(param_7 + iVar12 + 1) = *(int *)(param_7 + iVar12 + 1) + iVar12;
  piVar1 = (int *)((int)&puStack_2 + iVar8 + 1);
  *piVar1 = *piVar1 + iVar3;
  *(int *)(param_7 + iVar15) = *(int *)(param_7 + iVar15) + iVar15;
  *(int *)(iVar15 + param_6) = (int)(&stack0x4cf4 + *(int *)(iVar15 + param_6));
  *(int *)(iVar15 + param_6) = *(int *)(iVar15 + param_6) + iVar12;
  *(int *)(iVar15 + param_6) = *(int *)(iVar15 + param_6) + CONCAT11(cVar10,cVar9);
  *(int *)(iVar15 + param_6) = *(int *)(iVar15 + param_6) + iVar8;
  *(int *)(param_7 + iVar15) = *(int *)(param_7 + iVar15) + iVar3;
  cVar6 = (char)((uint)iVar3 >> 8) + cVar10;
  cVar4 = (char)iVar3 + cVar6;
  cVar11 = (char)(param_7 + iVar12);
  cVar7 = (char)iVar8 + cVar11;
  cVar11 = cVar11 + cVar9;
  cVar13 = (char)((uint)(param_7 + iVar12) >> 8) + cVar4;
  iVar12 = CONCAT11(cVar13,cVar11);
  *(char *)(param_6 + -0x4900) = *(char *)(param_6 + -0x4900) + cVar13;
  pcVar2 = (char *)(iVar15 + param_6 + -0x5400);
  *pcVar2 = *pcVar2 + cVar10 + cVar6;
  pcVar2 = (char *)(iVar12 + param_6 + -0x5d00);
  *pcVar2 = *pcVar2 + (char)((uint)iVar8 >> 8) * '\x02' + cVar7;
  (&stack0x99fe)[iVar8] = (&stack0x99fe)[iVar8] + cVar11;
  param_7[-0x6f00] = param_7[-0x6f00] + cVar9 + cVar4;
  param_7[-0x7700] = param_7[-0x7700] + cVar7;
  param_7[-0x7f00] = param_7[-0x7f00] + cVar4;
  *param_7 = *param_7 + cVar13;
  pcVar2 = (char *)(iVar12 + param_6);
  *pcVar2 = *pcVar2 + cVar7;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ---- driver-overlay runtime base (set at INT 21h AH=4B load; accessors add it) ---- */
uint32_t fist_snd_base = 0;
/* ---- module {offset -> &FUN} map, sorted for fist_icall overlay-range dispatch ---- */
const struct fist_fent fist_snd_fmap[] = {
  {0x0u,(void*)&app_entry},
  {0x4u,(void*)&FUN_0000_0004},
  {0x155u,(void*)&FUN_0000_0155},
  {0x19au,(void*)&FUN_0000_019a},
  {0x1bcu,(void*)&FUN_0000_01bc},
  {0x313u,(void*)&FUN_0000_0313},
  {0x5c4u,(void*)&FUN_0000_05c4},
  {0x5cau,(void*)&FUN_0000_05ca},
  {0x643u,(void*)&FUN_0000_0643},
  {0x714u,(void*)&FUN_0000_0714},
  {0x74fu,(void*)&FUN_0000_074f},
  {0x759u,(void*)&FUN_0000_0759},
  {0x772u,(void*)&FUN_0000_0772},
  {0x826u,(void*)&FUN_0000_0826},
  {0x833u,(void*)&FUN_0000_0833},
  {0x88fu,(void*)&FUN_0000_088f},
  {0x966u,(void*)&FUN_0000_0966},
  {0x997u,(void*)&FUN_0000_0997},
  {0xaa7u,(void*)&FUN_0000_0aa7},
  {0xaf0u,(void*)&FUN_0000_0af0},
  {0xaf4u,(void*)&FUN_0000_0af4},
  {0xb80u,(void*)&FUN_0000_0b80},
  {0xbf7u,(void*)&FUN_0000_0bf7},
  {0xc94u,(void*)&FUN_0000_0c94},
  {0xca9u,(void*)&FUN_0000_0ca9},
  {0xcd1u,(void*)&FUN_0000_0cd1},
  {0xcf3u,(void*)&FUN_0000_0cf3},
  {0xcfbu,(void*)&FUN_0000_0cfb},
  {0xd49u,(void*)&FUN_0000_0d49},
  {0xd66u,(void*)&FUN_0000_0d66},
  {0xd67u,(void*)&FUN_0000_0d67},
  {0xd90u,(void*)&FUN_0000_0d90},
  {0xdc9u,(void*)&FUN_0000_0dc9},
  {0xe94u,(void*)&FUN_0000_0e94},
  {0xef5u,(void*)&FUN_0000_0ef5},
  {0x1b3cu,(void*)&FUN_0000_1b3c},
  {0x1c8fu,(void*)&FUN_0000_1c8f},
  {0x216bu,(void*)&FUN_0000_216b},
  {0x2187u,(void*)&FUN_0000_2187},
  {0x2196u,(void*)&FUN_0000_2196},
  {0x224cu,(void*)&FUN_0000_224c},
  {0x2278u,(void*)&FUN_0000_2278},
  {0x25ebu,(void*)&FUN_0000_25eb},
  {0x386du,(void*)&FUN_0000_386d},
};
const unsigned fist_snd_fmap_n = sizeof(fist_snd_fmap)/sizeof(fist_snd_fmap[0]);
