[sdl]
fullscreen=false
output=surface
autolock=false
[render]
frameskip=0
aspect=false
scaler=none
[dosbox]
memsize=16
[cpu]
core=auto
cputype=auto
cycles=max
[autoexec]
mount c /home/cosmo/Git/wasm-fist/armoredfist
c:
LOADGAME -K400,0,1000 -X5000 FIST.RUN
